import { useState, useRef, useCallback } from "react";
import { SelectedPlan, ItineraryDay, Activity } from "@/types/travel";
import { Button } from "@/components/ui/button";
import { Checkbox } from "@/components/ui/checkbox";
import {
  Calendar, MapPin, Wallet, ArrowLeft, Plane, Sun, Sunset, Moon,
  UtensilsCrossed, Hotel, ArrowUp, ArrowDown, RefreshCw,
  FileText, MessageCircle, Clock, Lightbulb, Leaf, Star, AlertTriangle, Edit3, Check
} from "lucide-react";
import TripMap from "./TripMap";
import { getCurrencyForCountry, formatCurrency, requiresVisa } from "@/lib/currency";

interface ItineraryViewProps {
  plan: SelectedPlan;
  onStartOver: () => void;
  onRegenerate?: () => void;
}

const slotIcons: Record<string, any> = { Morning: Sun, Afternoon: Sunset, Evening: Moon };
const slotColors: Record<string, string> = {
  Morning: "from-amber-100 to-orange-100",
  Afternoon: "from-orange-100 to-rose-100",
  Evening: "from-indigo-100 to-purple-100",
};

const ItineraryView = ({ plan, onStartOver, onRegenerate }: ItineraryViewProps) => {
  const { cost_breakdown, itinerary: initialItinerary, destinations, reasoning, friendly_summary, stay_recommendations } = plan;
  const [itinerary, setItinerary] = useState<ItineraryDay[]>(() => normalizeItinerary(initialItinerary || []));
  const [activeDay, setActiveDay] = useState(0);
  const [activeTab, setActiveTab] = useState<"plan" | "food" | "stay" | "map">("plan");
  const itineraryRef = useRef<HTMLDivElement>(null);

  // Detect currency from first destination
  const primaryCountry = destinations[0]?.country || "India";
  const currency = getCurrencyForCountry(primaryCountry);
  const showVisaWarning = destinations.some((d) => requiresVisa(d.country));

  const costItems = [
    { label: "Flights", value: cost_breakdown?.flights_cost, icon: Plane },
    { label: "Stay", value: cost_breakdown?.accommodation_cost, icon: Hotel },
    { label: "Transport", value: cost_breakdown?.local_transport_cost, icon: MapPin },
    { label: "Activities", value: cost_breakdown?.activities_cost, icon: Calendar },
    { label: "Food", value: cost_breakdown?.food_cost || 0, icon: UtensilsCrossed },
    { label: "Buffer", value: cost_breakdown?.buffer, icon: Wallet },
  ];

  const toggleActivity = useCallback((dayIdx: number, slotIdx: number, actIdx: number) => {
    setItinerary((prev) => {
      const next = structuredClone(prev);
      const act = next[dayIdx].time_slots[slotIdx].activities[actIdx];
      act.selected = !act.selected;
      return next;
    });
  }, []);

  const updateActivityTitle = useCallback((dayIdx: number, slotIdx: number, actIdx: number, title: string) => {
    setItinerary((prev) => {
      const next = structuredClone(prev);
      next[dayIdx].time_slots[slotIdx].activities[actIdx].title = title;
      return next;
    });
  }, []);

  const updateActivityNotes = useCallback((dayIdx: number, slotIdx: number, actIdx: number, notes: string) => {
    setItinerary((prev) => {
      const next = structuredClone(prev);
      next[dayIdx].time_slots[slotIdx].activities[actIdx].notes = notes;
      return next;
    });
  }, []);

  const moveDay = (idx: number, dir: -1 | 1) => {
    const newIdx = idx + dir;
    if (newIdx < 0 || newIdx >= itinerary.length) return;
    const arr = [...itinerary];
    [arr[idx], arr[newIdx]] = [arr[newIdx], arr[idx]];
    arr.forEach((d, i) => (d.day = i + 1));
    setItinerary(arr);
    setActiveDay(newIdx);
  };

  const generateWhatsAppSummary = () => {
    let msg = `✈️ *My Trip Plan*\n\n`;
    msg += `📍 ${destinations.map((d) => `${d.city}, ${d.country}`).join(" → ")}\n`;
    msg += `💰 Total: ${formatCurrency(cost_breakdown?.total || 0, currency.code)}\n\n`;
    itinerary.forEach((day) => {
      msg += `*Day ${day.day}: ${day.location}*\n`;
      day.time_slots?.forEach((slot) => {
        const selected = slot.activities?.filter((a) => a.selected) || [];
        if (selected.length) {
          msg += `  ${slot.label}:\n`;
          selected.forEach((a) => { msg += `    ✅ ${a.time} - ${a.title}\n`; });
        }
      });
      msg += "\n";
    });
    msg += `_Generated by Wanderlust AI_ ✨`;
    window.open(`https://wa.me/?text=${encodeURIComponent(msg)}`, "_blank");
  };

  const generatePDFText = () => {
    let text = "TRIP ITINERARY\n" + "=".repeat(40) + "\n\n";
    text += `Destinations: ${destinations.map((d) => `${d.city}, ${d.country} (${d.days_allocated} days)`).join(" | ")}\n`;
    text += `Total Budget: ${formatCurrency(cost_breakdown?.total || 0, currency.code)}\n\n`;
    text += "-".repeat(40) + "\n";
    itinerary.forEach((day) => {
      text += `\nDAY ${day.day}: ${day.location}\n${day.plan}\n`;
      day.time_slots?.forEach((slot) => {
        text += `\n  ${slot.label}:\n`;
        slot.activities?.forEach((a) => {
          text += `    ${a.selected ? "✅" : "⬜"} ${a.time} - ${a.title} (${a.duration})\n`;
          if (a.notes) text += `      → ${a.notes}\n`;
        });
      });
      if (day.food_spots?.length) {
        text += `\n  🍽 Food:\n`;
        day.food_spots.forEach((f) => {
          text += `    ${f.name} - ${f.cuisine} (${f.price_range})\n`;
          if (f.must_try_dish) text += `      Must try: ${f.must_try_dish}\n`;
        });
      }
    });
    const blob = new Blob([text], { type: "text/plain" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = "trip-itinerary.txt";
    a.click();
    URL.revokeObjectURL(url);
  };

  const currentDay = itinerary[activeDay];

  // Group food by meal time
  const groupedFood = currentDay?.food_spots?.reduce((acc, spot) => {
    const meal = spot.meal_time || guessMealTime(spot);
    if (!acc[meal]) acc[meal] = [];
    acc[meal].push(spot);
    return acc;
  }, {} as Record<string, typeof currentDay.food_spots>) || {};

  return (
    <div className="min-h-screen px-4 py-8 max-w-5xl mx-auto" ref={itineraryRef}>
      {/* Header */}
      <div className="text-center mb-8 animate-fade-up">
        <h2 className="font-display text-3xl md:text-4xl font-bold text-foreground mb-2">Your Perfect Trip</h2>
        <p className="text-muted-foreground text-base max-w-xl mx-auto">{friendly_summary}</p>
      </div>

      {/* Visa Warning */}
      {showVisaWarning && (
        <div className="glass-card p-4 mb-6 flex items-center gap-3 border border-amber-300 bg-amber-50 animate-fade-up">
          <AlertTriangle className="w-5 h-5 text-amber-600 shrink-0" />
          <p className="text-sm text-amber-800">
            ⚠️ This destination may require a visa. Please check travel requirements before booking.
          </p>
        </div>
      )}

      {/* Destinations chips */}
      <div className="flex flex-wrap justify-center gap-3 mb-6 animate-fade-up" style={{ animationDelay: "0.1s" }}>
        {destinations.map((d) => (
          <div key={d.city} className="glass-card px-5 py-3 text-center">
            <h3 className="font-display text-lg font-semibold text-foreground">{d.city}, {d.country}</h3>
            <p className="text-xs text-muted-foreground">{d.days_allocated} days · {getCurrencyForCountry(d.country).code}</p>
          </div>
        ))}
      </div>

      {/* Cost breakdown */}
      <div className="glass-card p-5 mb-6 animate-fade-up" style={{ animationDelay: "0.15s" }}>
        <h3 className="font-display text-lg font-semibold text-foreground mb-3 flex items-center gap-2">
          <Wallet className="w-5 h-5 text-primary" /> Budget Breakdown
        </h3>
        <div className="grid grid-cols-3 md:grid-cols-6 gap-3 mb-3">
          {costItems.map((item) => (
            <div key={item.label} className="text-center">
              <item.icon className="w-4 h-4 text-primary mx-auto mb-1" />
              <p className="text-xs text-muted-foreground">{item.label}</p>
              <p className="text-sm font-semibold text-foreground">{formatCurrency(item.value || 0, currency.code)}</p>
            </div>
          ))}
        </div>
        <div className="border-t border-border pt-2 text-center">
          <p className="text-2xl font-bold text-primary">{formatCurrency(cost_breakdown?.total || 0, currency.code)}</p>
        </div>
      </div>

      {/* Tab bar */}
      <div className="flex gap-2 mb-4 overflow-x-auto">
        {(["plan", "food", "stay", "map"] as const).map((tab) => (
          <button
            key={tab}
            onClick={() => setActiveTab(tab)}
            className={`px-4 py-2 rounded-xl text-sm font-medium transition-colors whitespace-nowrap ${
              activeTab === tab ? "bg-primary text-primary-foreground" : "bg-secondary text-secondary-foreground hover:bg-primary/10"
            }`}
          >
            {tab === "plan" ? "📅 Day Plan" : tab === "food" ? "🍽 Food" : tab === "stay" ? "🏨 Stay" : "🗺 Map"}
          </button>
        ))}
      </div>

      {/* Day selector */}
      {activeTab !== "stay" && activeTab !== "map" && (
        <div className="flex gap-2 mb-5 overflow-x-auto pb-2">
          {itinerary.map((day, i) => (
            <button
              key={day.day}
              onClick={() => setActiveDay(i)}
              className={`flex-shrink-0 px-4 py-2 rounded-xl text-sm font-medium transition-all ${
                activeDay === i ? "gradient-warm text-primary-foreground shadow-md" : "glass-card text-foreground hover:shadow-sm"
              }`}
            >
              Day {day.day}
              <span className="block text-xs opacity-75">{day.location}</span>
            </button>
          ))}
        </div>
      )}

      {/* Plan tab */}
      {activeTab === "plan" && currentDay && (
        <div className="space-y-4 animate-fade-up">
          <div className="flex items-center justify-between">
            <div>
              <h3 className="font-display text-xl font-semibold text-foreground">
                Day {currentDay.day}: {currentDay.location}
              </h3>
              <p className="text-sm text-muted-foreground">{currentDay.plan}</p>
            </div>
            <div className="flex gap-1">
              <Button variant="ghost" size="icon" onClick={() => moveDay(activeDay, -1)} disabled={activeDay === 0}>
                <ArrowUp className="w-4 h-4" />
              </Button>
              <Button variant="ghost" size="icon" onClick={() => moveDay(activeDay, 1)} disabled={activeDay === itinerary.length - 1}>
                <ArrowDown className="w-4 h-4" />
              </Button>
            </div>
          </div>

          {currentDay.time_slots?.map((slot, slotIdx) => {
            const SlotIcon = slotIcons[slot.label] || Sun;
            return (
              <div key={slot.label} className="glass-card overflow-hidden">
                <div className={`bg-gradient-to-r ${slotColors[slot.label] || ""} px-4 py-2 flex items-center gap-2`}>
                  <SlotIcon className="w-4 h-4 text-foreground" />
                  <span className="text-sm font-semibold text-foreground">{slot.label}</span>
                  <span className="text-xs text-muted-foreground ml-auto">
                    {slot.activities?.filter((a) => a.selected).length || 0}/{slot.activities?.length || 0} selected
                  </span>
                </div>
                <div className="p-4 space-y-3">
                  {slot.activities?.map((activity, ai) => (
                    <ActivityCard
                      key={activity.id}
                      activity={activity}
                      onToggle={() => toggleActivity(activeDay, slotIdx, ai)}
                      onUpdateTitle={(t) => updateActivityTitle(activeDay, slotIdx, ai, t)}
                      onUpdateNotes={(n) => updateActivityNotes(activeDay, slotIdx, ai, n)}
                    />
                  ))}
                  {(!slot.activities || slot.activities.length === 0) && (
                    <p className="text-sm text-muted-foreground italic">Free time — explore on your own!</p>
                  )}
                </div>
              </div>
            );
          })}

          {currentDay.travel_tip && (
            <div className="glass-card p-4 flex items-start gap-3 bg-primary/5">
              <Lightbulb className="w-5 h-5 text-primary shrink-0 mt-0.5" />
              <p className="text-sm text-foreground">{currentDay.travel_tip}</p>
            </div>
          )}
        </div>
      )}

      {/* Food tab — grouped by meal time */}
      {activeTab === "food" && currentDay && (
        <div className="space-y-5 animate-fade-up">
          <h3 className="font-display text-lg font-semibold text-foreground mb-2">
            Day {currentDay.day} — Food Recommendations
          </h3>
          {(["morning", "afternoon", "dinner"] as const).map((meal) => {
            const spots = groupedFood[meal];
            if (!spots?.length) return null;
            return (
              <div key={meal}>
                <h4 className="text-sm font-semibold text-foreground mb-2 capitalize flex items-center gap-2">
                  {meal === "morning" ? "🌅" : meal === "afternoon" ? "☀️" : "🌙"} {meal}
                </h4>
                <div className="space-y-3">
                  {spots.map((spot, i) => (
                    <div key={i} className="glass-card p-4">
                      <div className="flex items-start justify-between mb-1">
                        <h4 className="font-semibold text-foreground">{spot.name}</h4>
                        <span className="text-xs text-muted-foreground">{spot.price_range}</span>
                      </div>
                      <p className="text-sm text-muted-foreground mb-2">{spot.cuisine}</p>
                      {spot.must_try_dish && (
                        <p className="text-sm text-primary flex items-center gap-1">
                          <Star className="w-3 h-3" /> Must try: {spot.must_try_dish}
                        </p>
                      )}
                      <div className="flex flex-wrap gap-1.5 mt-2">
                        {spot.dietary_tags?.filter(isNonReligiousTag).map((tag) => (
                          <span key={tag} className="text-xs px-2 py-0.5 rounded-full bg-green-100 text-green-700 flex items-center gap-1">
                            <Leaf className="w-2.5 h-2.5" /> {tag}
                          </span>
                        ))}
                      </div>
                    </div>
                  ))}
                </div>
              </div>
            );
          })}
          {Object.keys(groupedFood).length === 0 && (
            <p className="text-sm text-muted-foreground italic">No specific food recommendations for this day.</p>
          )}
        </div>
      )}

      {/* Stay tab */}
      {activeTab === "stay" && (
        <div className="space-y-3 animate-fade-up">
          <h3 className="font-display text-lg font-semibold text-foreground mb-2">Where to Stay</h3>
          {stay_recommendations?.map((stay, i) => (
            <div key={i} className="glass-card p-4">
              <div className="flex items-start justify-between mb-1">
                <h4 className="font-semibold text-foreground">{stay.area}</h4>
                <span className={`text-xs px-2 py-0.5 rounded-full ${
                  stay.budget_tier === "budget" ? "bg-green-100 text-green-700" :
                  stay.budget_tier === "luxury" ? "bg-amber-100 text-amber-700" :
                  "bg-blue-100 text-blue-700"
                }`}>
                  {stay.budget_tier}
                </span>
              </div>
              <p className="text-sm text-muted-foreground mb-2">{stay.why}</p>
              <p className="text-sm text-primary font-medium mb-2">~{formatCurrency(stay.price_per_night_estimate || 0, currency.code)}/night</p>
              <div className="flex flex-wrap gap-1.5">
                {stay.tags?.map((tag) => (
                  <span key={tag} className="text-xs px-2 py-0.5 rounded-full bg-secondary text-secondary-foreground">{tag}</span>
                ))}
              </div>
            </div>
          ))}
          {(!stay_recommendations || stay_recommendations.length === 0) && (
            <p className="text-sm text-muted-foreground italic">No stay recommendations available.</p>
          )}
        </div>
      )}

      {/* Map tab */}
      {activeTab === "map" && (
        <div className="animate-fade-up">
          <TripMap itinerary={itinerary} destinations={destinations} />
        </div>
      )}

      {/* Reasoning */}
      <div className="glass-card p-5 mt-6 animate-fade-up">
        <h3 className="font-display text-lg font-semibold text-foreground mb-2">Why this plan?</h3>
        <p className="text-sm text-muted-foreground mb-1">{reasoning?.selection_reason}</p>
        <p className="text-sm text-muted-foreground italic">Tradeoffs: {reasoning?.tradeoffs}</p>
      </div>

      {/* Actions */}
      <div className="flex flex-wrap justify-center gap-3 mt-8">
        <Button variant="warm" onClick={generatePDFText} className="gap-2">
          <FileText className="w-4 h-4" /> Export as Text
        </Button>
        <Button variant="warm" onClick={generateWhatsAppSummary} className="gap-2">
          <MessageCircle className="w-4 h-4" /> Share on WhatsApp
        </Button>
        {onRegenerate && (
          <Button variant="warm" onClick={onRegenerate} className="gap-2">
            <RefreshCw className="w-4 h-4" /> Regenerate Plan
          </Button>
        )}
        <Button variant="warm" onClick={onStartOver} className="gap-2">
          <ArrowLeft className="w-4 h-4" /> Plan Another Trip
        </Button>
      </div>
    </div>
  );
};

// --- Activity Card with checkbox + inline editing ---

interface ActivityCardProps {
  activity: Activity;
  onToggle: () => void;
  onUpdateTitle: (title: string) => void;
  onUpdateNotes: (notes: string) => void;
}

const ActivityCard = ({ activity, onToggle, onUpdateTitle, onUpdateNotes }: ActivityCardProps) => {
  const [editing, setEditing] = useState(false);
  const [title, setTitle] = useState(activity.title);
  const [notes, setNotes] = useState(activity.notes || "");

  const saveEdit = () => {
    onUpdateTitle(title);
    onUpdateNotes(notes);
    setEditing(false);
  };

  return (
    <div className={`flex items-start gap-3 p-2 rounded-lg transition-colors ${activity.selected ? "bg-primary/5" : "opacity-60"}`}>
      <Checkbox
        checked={activity.selected}
        onCheckedChange={onToggle}
        className="mt-1"
      />
      <div className="text-xs text-muted-foreground w-16 shrink-0 pt-0.5 flex items-center gap-1">
        <Clock className="w-3 h-3" />
        {activity.time}
      </div>
      <div className="flex-1">
        {editing ? (
          <div className="space-y-1">
            <input
              value={title}
              onChange={(e) => setTitle(e.target.value)}
              className="w-full text-sm font-medium bg-background border border-border rounded px-2 py-1 text-foreground focus:outline-none focus:ring-1 focus:ring-primary"
            />
            <input
              value={notes}
              onChange={(e) => setNotes(e.target.value)}
              placeholder="Notes..."
              className="w-full text-xs bg-background border border-border rounded px-2 py-1 text-muted-foreground focus:outline-none focus:ring-1 focus:ring-primary"
            />
            <Button variant="ghost" size="sm" onClick={saveEdit} className="h-6 text-xs gap-1">
              <Check className="w-3 h-3" /> Save
            </Button>
          </div>
        ) : (
          <>
            <div className="flex items-center gap-2">
              <p className="text-sm font-medium text-foreground">{activity.title}</p>
              <button onClick={() => setEditing(true)} className="text-muted-foreground hover:text-primary transition-colors">
                <Edit3 className="w-3 h-3" />
              </button>
            </div>
            <p className="text-xs text-muted-foreground">{activity.duration}</p>
            {activity.notes && <p className="text-xs text-muted-foreground mt-0.5">{activity.notes}</p>}
            {activity.dietary_tags?.length ? (
              <div className="flex gap-1 mt-1">
                {activity.dietary_tags.map((t) => (
                  <span key={t} className="text-xs px-1.5 py-0.5 rounded bg-green-100 text-green-700">{t}</span>
                ))}
              </div>
            ) : null}
          </>
        )}
      </div>
    </div>
  );
};

// --- Helpers ---

function normalizeItinerary(days: ItineraryDay[]): ItineraryDay[] {
  return days.map((day) => ({
    ...day,
    time_slots: (day.time_slots || []).map((slot) => ({
      ...slot,
      activities: (slot.activities || []).map((a, idx) => ({
        ...a,
        id: a.id || `${day.day}-${slot.label}-${idx}`,
        selected: a.selected !== false,
      })),
    })),
    food_spots: (day.food_spots || []).map((f) => ({
      ...f,
      meal_time: f.meal_time || guessMealTime(f),
    })),
  }));
}

function guessMealTime(spot: any): "morning" | "afternoon" | "dinner" {
  const name = (spot.name + " " + (spot.cuisine || "")).toLowerCase();
  if (name.includes("breakfast") || name.includes("brunch") || name.includes("cafe") || name.includes("coffee")) return "morning";
  if (name.includes("dinner") || name.includes("bar") || name.includes("night")) return "dinner";
  return "afternoon";
}

function isNonReligiousTag(tag: string): boolean {
  const lower = tag.toLowerCase();
  return !["halal", "kosher", "haram"].includes(lower);
}

export default ItineraryView;
