import { useState, useRef, useCallback, useEffect } from "react";
import { SelectedPlan, ItineraryDay, TimeSlot } from "@/types/travel";
import { Button } from "@/components/ui/button";
import {
  Wallet, ArrowLeft, Plane, Sun, Sunset, Moon,
  MapPin, Calendar, Hotel, ArrowUp, ArrowDown,
  UtensilsCrossed, FileText, MessageCircle, Lightbulb, Leaf, Star, Save
} from "lucide-react";
import { toast } from "sonner";
import { supabase } from "@/integrations/supabase/client";
import TripMap from "./TripMap";
import EditableTimeSlot from "./EditableTimeSlot";

interface ItineraryViewProps {
  plan: SelectedPlan;
  onStartOver: () => void;
  tripId?: string;
}

const ItineraryView = ({ plan, onStartOver, tripId }: ItineraryViewProps) => {
  const { cost_breakdown, itinerary: initialItinerary, destinations, reasoning, friendly_summary, stay_recommendations } = plan;
  const [itinerary, setItinerary] = useState<ItineraryDay[]>(initialItinerary || []);
  const [activeDay, setActiveDay] = useState(0);
  const [activeTab, setActiveTab] = useState<"plan" | "food" | "stay" | "map">("plan");
  const [hasUnsaved, setHasUnsaved] = useState(false);
  const [saving, setSaving] = useState(false);
  const itineraryRef = useRef<HTMLDivElement>(null);

  const costItems = [
    { label: "Flights", value: cost_breakdown?.flights_cost, icon: Plane },
    { label: "Stay", value: cost_breakdown?.accommodation_cost, icon: Hotel },
    { label: "Transport", value: cost_breakdown?.local_transport_cost, icon: MapPin },
    { label: "Activities", value: cost_breakdown?.activities_cost, icon: Calendar },
    { label: "Food", value: cost_breakdown?.food_cost || 0, icon: UtensilsCrossed },
    { label: "Buffer", value: cost_breakdown?.buffer, icon: Wallet },
  ];

  const updateItinerary = useCallback((newItinerary: ItineraryDay[]) => {
    setItinerary(newItinerary);
    setHasUnsaved(true);
  }, []);

  const saveToDatabase = useCallback(async () => {
    if (!tripId) return;
    setSaving(true);
    try {
      const updatedPlan: SelectedPlan = { ...plan, itinerary };
      const { error } = await supabase
        .from("trips")
        .update({ itinerary_data: updatedPlan as any })
        .eq("id", tripId);
      if (error) throw error;
      setHasUnsaved(false);
      toast.success("Changes saved!");
    } catch (e: any) {
      toast.error("Failed to save changes");
      console.error(e);
    } finally {
      setSaving(false);
    }
  }, [tripId, itinerary, plan]);

  const moveDay = (idx: number, dir: -1 | 1) => {
    const newIdx = idx + dir;
    if (newIdx < 0 || newIdx >= itinerary.length) return;
    const arr = [...itinerary];
    [arr[idx], arr[newIdx]] = [arr[newIdx], arr[idx]];
    arr.forEach((d, i) => (d.day = i + 1));
    updateItinerary(arr);
    setActiveDay(newIdx);
  };

  const handleSlotChange = useCallback((slotIdx: number, updatedSlot: TimeSlot) => {
    const day = { ...itinerary[activeDay] };
    const slots = [...(day.time_slots || [])];
    slots[slotIdx] = updatedSlot;
    day.time_slots = slots;
    const arr = [...itinerary];
    arr[activeDay] = day;
    updateItinerary(arr);
  }, [itinerary, activeDay, updateItinerary]);

  const generateWhatsAppSummary = () => {
    let msg = `✈️ *My Trip Plan*\n\n`;
    msg += `📍 ${destinations.map((d) => `${d.city}, ${d.country}`).join(" → ")}\n`;
    msg += `💰 Total: ₹${cost_breakdown?.total?.toLocaleString() || 0}\n\n`;
    itinerary.forEach((day) => {
      msg += `*Day ${day.day}: ${day.location}*\n${day.plan}\n\n`;
    });
    msg += `_Generated by Wanderlust AI_ ✨`;
    window.open(`https://wa.me/?text=${encodeURIComponent(msg)}`, "_blank");
  };

  const generatePDFText = () => {
    let text = "TRIP ITINERARY\n" + "=".repeat(40) + "\n\n";
    text += `Destinations: ${destinations.map((d) => `${d.city}, ${d.country} (${d.days_allocated} days)`).join(" | ")}\n`;
    text += `Total Budget: ₹${cost_breakdown?.total?.toLocaleString() || 0}\n\n` + "-".repeat(40) + "\n";
    itinerary.forEach((day) => {
      text += `\nDAY ${day.day}: ${day.location}\n${day.plan}\n`;
      day.time_slots?.forEach((slot) => {
        text += `\n  ${slot.label}:\n`;
        slot.activities?.forEach((a) => {
          text += `    ${a.time} - ${a.title} (${a.duration})\n`;
          if (a.notes) text += `      → ${a.notes}\n`;
        });
      });
      if (day.food_spots?.length) {
        text += `\n  🍽 Food:\n`;
        day.food_spots.forEach((f) => {
          text += `    ${f.name} - ${f.cuisine} (${f.price_range})\n`;
          if (f.must_try_dish) text += `      Must try: ${f.must_try_dish}\n`;
        });
      }
    });
    const blob = new Blob([text], { type: "text/plain" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = "trip-itinerary.txt";
    a.click();
    URL.revokeObjectURL(url);
  };

  const currentDay = itinerary[activeDay];

  return (
    <div className="min-h-screen px-4 py-8 max-w-5xl mx-auto" ref={itineraryRef}>
      {/* Header */}
      <div className="text-center mb-8 animate-fade-up">
        <h2 className="font-display text-3xl md:text-4xl font-bold text-foreground mb-2">Your Perfect Trip</h2>
        <p className="text-muted-foreground text-base max-w-xl mx-auto">{friendly_summary}</p>
      </div>

      {/* Destinations chips */}
      <div className="flex flex-wrap justify-center gap-3 mb-6 animate-fade-up" style={{ animationDelay: "0.1s" }}>
        {destinations.map((d) => (
          <div key={d.city} className="glass-card px-5 py-3 text-center">
            <h3 className="font-display text-lg font-semibold text-foreground">{d.city}, {d.country}</h3>
            <p className="text-xs text-muted-foreground">{d.days_allocated} days</p>
          </div>
        ))}
      </div>

      {/* Cost breakdown */}
      <div className="glass-card p-5 mb-6 animate-fade-up" style={{ animationDelay: "0.15s" }}>
        <h3 className="font-display text-lg font-semibold text-foreground mb-3 flex items-center gap-2">
          <Wallet className="w-5 h-5 text-primary" /> Budget Breakdown
        </h3>
        <div className="grid grid-cols-3 md:grid-cols-6 gap-3 mb-3">
          {costItems.map((item) => (
            <div key={item.label} className="text-center">
              <item.icon className="w-4 h-4 text-primary mx-auto mb-1" />
              <p className="text-xs text-muted-foreground">{item.label}</p>
              <p className="text-sm font-semibold text-foreground">₹{item.value?.toLocaleString() || 0}</p>
            </div>
          ))}
        </div>
        <div className="border-t border-border pt-2 text-center">
          <p className="text-2xl font-bold text-primary">₹{cost_breakdown?.total?.toLocaleString() || 0}</p>
        </div>
      </div>

      {/* Save indicator + Tab bar */}
      <div className="flex items-center justify-between mb-4">
        <div className="flex gap-2 overflow-x-auto">
          {(["plan", "food", "stay", "map"] as const).map((tab) => (
            <button
              key={tab}
              onClick={() => setActiveTab(tab)}
              className={`px-4 py-2 rounded-xl text-sm font-medium transition-colors whitespace-nowrap ${
                activeTab === tab ? "bg-primary text-primary-foreground" : "bg-secondary text-secondary-foreground hover:bg-primary/10"
              }`}
            >
              {tab === "plan" ? "📅 Day Plan" : tab === "food" ? "🍽 Food" : tab === "stay" ? "🏨 Stay" : "🗺 Map"}
            </button>
          ))}
        </div>
        {hasUnsaved && tripId && (
          <Button variant="default" size="sm" onClick={saveToDatabase} disabled={saving} className="gap-1.5 shrink-0">
            <Save className="w-3.5 h-3.5" />
            {saving ? "Saving..." : "Save"}
          </Button>
        )}
      </div>

      {/* Day selector */}
      {activeTab !== "stay" && activeTab !== "map" && (
        <div className="flex gap-2 mb-5 overflow-x-auto pb-2">
          {itinerary.map((day, i) => (
            <button
              key={day.day}
              onClick={() => setActiveDay(i)}
              className={`flex-shrink-0 px-4 py-2 rounded-xl text-sm font-medium transition-all ${
                activeDay === i ? "gradient-warm text-primary-foreground shadow-md" : "glass-card text-foreground hover:shadow-sm"
              }`}
            >
              Day {day.day}
              <span className="block text-xs opacity-75">{day.location}</span>
            </button>
          ))}
        </div>
      )}

      {/* Plan tab */}
      {activeTab === "plan" && currentDay && (
        <div className="space-y-4 animate-fade-up">
          <div className="flex items-center justify-between">
            <div>
              <h3 className="font-display text-xl font-semibold text-foreground">
                Day {currentDay.day}: {currentDay.location}
              </h3>
              <p className="text-sm text-muted-foreground">{currentDay.plan}</p>
            </div>
            <div className="flex gap-1">
              <Button variant="ghost" size="icon" onClick={() => moveDay(activeDay, -1)} disabled={activeDay === 0}>
                <ArrowUp className="w-4 h-4" />
              </Button>
              <Button variant="ghost" size="icon" onClick={() => moveDay(activeDay, 1)} disabled={activeDay === itinerary.length - 1}>
                <ArrowDown className="w-4 h-4" />
              </Button>
            </div>
          </div>

          {/* Editable time slots */}
          {currentDay.time_slots?.map((slot, si) => (
            <EditableTimeSlot
              key={slot.label}
              slot={slot}
              onSlotChange={(updated) => handleSlotChange(si, updated)}
            />
          ))}

          {currentDay.travel_tip && (
            <div className="glass-card p-4 flex items-start gap-3 bg-primary/5">
              <Lightbulb className="w-5 h-5 text-primary shrink-0 mt-0.5" />
              <p className="text-sm text-foreground">{currentDay.travel_tip}</p>
            </div>
          )}

          {!currentDay.time_slots?.length && (
            <div className="glass-card p-4">
              <p className="text-sm text-foreground">{currentDay.plan}</p>
            </div>
          )}
        </div>
      )}

      {/* Food tab */}
      {activeTab === "food" && currentDay && (
        <div className="space-y-3 animate-fade-up">
          <h3 className="font-display text-lg font-semibold text-foreground mb-2">
            Day {currentDay.day} — Food Recommendations
          </h3>
          {currentDay.food_spots?.map((spot, i) => (
            <div key={i} className="glass-card p-4">
              <div className="flex items-start justify-between mb-1">
                <h4 className="font-semibold text-foreground">{spot.name}</h4>
                <span className="text-xs text-muted-foreground">{spot.price_range}</span>
              </div>
              <p className="text-sm text-muted-foreground mb-2">{spot.cuisine}</p>
              {spot.must_try_dish && (
                <p className="text-sm text-primary flex items-center gap-1">
                  <Star className="w-3 h-3" /> Must try: {spot.must_try_dish}
                </p>
              )}
              <div className="flex flex-wrap gap-1.5 mt-2">
                {spot.dietary_tags?.map((tag) => (
                  <span key={tag} className="text-xs px-2 py-0.5 rounded-full bg-green-100 text-green-700 flex items-center gap-1">
                    <Leaf className="w-2.5 h-2.5" /> {tag}
                  </span>
                ))}
              </div>
            </div>
          ))}
          {(!currentDay.food_spots || currentDay.food_spots.length === 0) && (
            <p className="text-sm text-muted-foreground italic">No specific food recommendations for this day.</p>
          )}
        </div>
      )}

      {/* Stay tab */}
      {activeTab === "stay" && (
        <div className="space-y-3 animate-fade-up">
          <h3 className="font-display text-lg font-semibold text-foreground mb-2">Where to Stay</h3>
          {stay_recommendations?.map((stay, i) => (
            <div key={i} className="glass-card p-4">
              <div className="flex items-start justify-between mb-1">
                <h4 className="font-semibold text-foreground">{stay.area}</h4>
                <span className={`text-xs px-2 py-0.5 rounded-full ${
                  stay.budget_tier === "budget" ? "bg-green-100 text-green-700" :
                  stay.budget_tier === "luxury" ? "bg-amber-100 text-amber-700" :
                  "bg-blue-100 text-blue-700"
                }`}>
                  {stay.budget_tier}
                </span>
              </div>
              <p className="text-sm text-muted-foreground mb-2">{stay.why}</p>
              <p className="text-sm text-primary font-medium mb-2">~₹{stay.price_per_night_estimate?.toLocaleString()}/night</p>
              <div className="flex flex-wrap gap-1.5">
                {stay.tags?.map((tag) => (
                  <span key={tag} className="text-xs px-2 py-0.5 rounded-full bg-secondary text-secondary-foreground">
                    {tag}
                  </span>
                ))}
              </div>
            </div>
          ))}
          {(!stay_recommendations || stay_recommendations.length === 0) && (
            <p className="text-sm text-muted-foreground italic">No stay recommendations available.</p>
          )}
        </div>
      )}

      {/* Map tab */}
      {activeTab === "map" && (
        <div className="animate-fade-up">
          <TripMap itinerary={itinerary} destinations={destinations} />
        </div>
      )}

      {/* Reasoning */}
      <div className="glass-card p-5 mt-6 animate-fade-up">
        <h3 className="font-display text-lg font-semibold text-foreground mb-2">Why this plan?</h3>
        <p className="text-sm text-muted-foreground mb-1">{reasoning?.selection_reason}</p>
        <p className="text-sm text-muted-foreground italic">Tradeoffs: {reasoning?.tradeoffs}</p>
      </div>

      {/* Actions */}
      <div className="flex flex-wrap justify-center gap-3 mt-8">
        {hasUnsaved && tripId && (
          <Button variant="default" onClick={saveToDatabase} disabled={saving} className="gap-2">
            <Save className="w-4 h-4" /> {saving ? "Saving..." : "Save Changes"}
          </Button>
        )}
        <Button variant="warm" onClick={generatePDFText} className="gap-2">
          <FileText className="w-4 h-4" /> Export as Text
        </Button>
        <Button variant="warm" onClick={generateWhatsAppSummary} className="gap-2">
          <MessageCircle className="w-4 h-4" /> Share on WhatsApp
        </Button>
        <Button variant="warm" onClick={onStartOver} className="gap-2">
          <ArrowLeft className="w-4 h-4" /> Plan Another Trip
        </Button>
      </div>
    </div>
  );
};

export default ItineraryView;
